### ISSUE TITLE
Qt wrapper

### ISSUE THREAD

**Issue by ocgltd** [spdawson/lcdapi#5]
I'm not sure if this would be better as a fork, or a conditional compile, but adding Qt5 support would be really nice.  Use of the Qt event loop (instead of sleep), using signals for key arrival, using the network library of Qt would all make this a lot more friend for users coming form the Qt/C++ world.  Just a suggestion - but nice project!

**Comment by spdawson** [comment]
While this is a very nice idea, sadly I'm not going to be able to find time to work on it in the near future.
