### ISSUE TITLE
Client backlight

### ISSUE THREAD

**Issue by terba** [spdawson/lcdapi#8]
Hello,

I would like to set the clients backlight instead of the screen's. But there is no method for that in the LCDClient class.

Excerpt from LCDproc Developer's Guide:

> Miscellaneous
> 
> backlight { on | off | toggle | blink | flash }
> 
>   Sets the client's backlight state. 

Thanks in advance!

**Comment by spdawson** [comment]
Released v0.12 with `LCDClient#setBacklight` implemented

**Comment by terba** [comment]
Thank you!
